### ISSUE TITLE
Could you provide a 3D point cloud example?

### ISSUE THREAD

**Issue by cdb0y511** [bernhard-schmitzer/MultiScaleOT#1]
Hi,@bernhard-schmitzer. Thanks for your great work.
Recently, I am looking forward to replacing the network simplex algorithm to solve OT problem. I want to pair two point clouds (x,y,z coordinates, in the euclidian distance) under OT assumptions. Then the displacement interpolation between two point clouds can be derived. So I am interested in your C++ implementation, 
1.could provide an example for 3d point cloud? 
2. I think the Sinkhorn kind OT may result in a dense transport plan, however, the sparse one is required (for displacement interpolation), how can I get the sparse one?
Thanks,

**Comment by bernhard-schmitzer** [comment]
Hey, just added a few more examples to the documentation that hopefully cover the questions, e.g. how to compute OT between two point clouds in 3d, and how to do some post-processing on the optimal solution. You can also have a look at the 2d displacement interpolation example. Maybe it helps. Let me know if you still have problems.
At the end of the day, the algorithm will always be a little bit fragile.
